### ISSUE TITLE
problem when run the main.py in the example fold.

### ISSUE THREAD

**Issue by Davidguo1229** [dorian-li/dvmss#1]
I install all the required lib (including deinterf and sgl2020, they can run well). but when I run the  main.py in the example fold, there is a problem . The error is as follows:
Traceback (most recent call last):
  File "C:\Users\11937\pytest\dvmss-test\example\main.py", line 12, in <module>
    flt_d = surv.source(
  File "C:\Users\11937\pytest\dvmss-test\example\sgl2020\data_wrapping.py", line 107, in take
    taken = self.data[self.data["line"].isin(self.line)][self.source]
  File "C:\Users\11937\.conda\envs\py310\lib\site-packages\pandas\core\series.py", line 5346, in isin
    result = algorithms.isin(self._values, values)
  File "C:\Users\11937\.conda\envs\py310\lib\site-packages\pandas\core\algorithms.py", line 477, in isin
    raise TypeError(
TypeError: only list-like objects are allowed to be passed to isin(), you passed a `method`

**Comment by dyuu7** [comment]
The issue has been resolved. Simply reinstall sgl2020. The problem arose because the dvmss example did not select a specific flight line, and sgl2020 failed to default to selecting all flight lines when there was data cache, leading to the absence of _line. This logic has now been fixed.

**Comment by dyuu7** [comment]
Currently, only deinterf has been effectively maintained. The dvmss and sgl2020 projects have not been organized yet, and the logic of the simulation may be incorrect. I will refactor and fix these when I have time. It is advisable to use them with caution.
